/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_doom119_nativegl_OpenGL */

#ifndef _Included_com_doom119_nativegl_OpenGL
#define _Included_com_doom119_nativegl_OpenGL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_doom119_nativegl_OpenGL
 * Method:    init
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_doom119_nativegl_OpenGL_init
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_doom119_nativegl_OpenGL
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_doom119_nativegl_OpenGL_draw
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
